# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('review', '0002_auto_20161123_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommended',
            field=models.BooleanField(default=0, verbose_name='Would you recommend it to your friend?'),
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
