# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20161204_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='laundry_onsite',
            field=models.NullBooleanField(default=1, verbose_name='is Laundry onsite?'),
        ),
        migrations.AddField(
            model_name='review',
            name='lived_from',
            field=models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015)], default=2016, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='review',
            name='lived_to',
            field=models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015)], default=2016, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Review the house'),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommended',
            field=models.BooleanField(default=1, verbose_name='Would you recommend it to your friend?'),
        ),
    ]
