# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20161204_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommended',
            field=models.NullBooleanField(default=1, verbose_name='Would you recommend it to your friend?'),
        ),
    ]
