# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20161204_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='baths',
            field=models.IntegerField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5)], default=1, null=True, verbose_name='Baths'),
        ),
        migrations.AddField(
            model_name='review',
            name='beds',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True, verbose_name='Beds'),
        ),
        migrations.AddField(
            model_name='review',
            name='rent',
            field=models.IntegerField(null=True, verbose_name='Rent'),
        ),
    ]
