# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20161206_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subboard_listing_ids',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
