# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_review_subboard_listing_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='subboard_listing_ids',
        ),
    ]
